### PR TITLE
feat: Cracked properties

### PR DESCRIPTION
**Pull request by MestreCarlos**
```python
from shapely import Polygon
from shapely.geometry import Polygon

from structuralcodes import codes, materials
from structuralcodes.geometry import SurfaceGeometry
from structuralcodes.sections._generic import GenericSection
from structuralcodes.sections._reinforcement import add_reinforcement_line

# from structuralcodes.plots.section_plots import draw_section_response,draw_section,get_stress_point

### CREATE THE SECTION ########
codes.set_design_code(design_code='ec2_2004')
concrete = materials.concrete.create_concrete(fck=25)
reinforcemnet = materials.reinforcement.create_reinforcement(
    fyk=500,
    Es=200000,
    density=7850,
    ftk=500,
    epsuk=0.07,
)
poly = Polygon(((0, 0), (350, 0), (350, 500), (0, 500)))
geo = SurfaceGeometry(poly, concrete)
geo = add_reinforcement_line(
    geo, (50, 450), (300, 450), 12, reinforcemnet, n=3
)
geo = add_reinforcement_line(geo, (50, 50), (300, 50), 20, reinforcemnet, n=6)
sec = GenericSection(
    geo,
)
sec.geometry = sec.geometry.translate(-175, -250)

)
### CREATE THE SECTION ########

print(sec.cracked_properties)
# print(sec.cracked_properties.i_yy_2 / sec.gross_properties.i11)
```

### CODE REVIEW

**Comment by MestreCarlos** [comment]
I updated the branch for review:

GenericSection.cracked_properties(n_ed=0, m_ed_1=0, m_ed_2=0)  -> s_res.CrackedProperties:
        """Return the cracked properties of the section for positive and
        negative bending (n=0) with horizontal neutral axe.
        n_ed = axial load in SLS
        m_ed_1 = moment in SLS compressing the bottom part of the section (>0).
        m_ed_2 = moment in SLS compressing the upper part of the section (<0).
        """

The output looks like this. If forces in SLS are do not reach fctm of concrete returns the gross properties

#############################################
Cracked concrete section properties for SLS forces:
 - N = -300000.0
 - M1 (compression on bottom) = 30000000.0
 - M2 (compression on top) = -60000000.0
1) No cracking expected for N+M1. Properties:      
  Product moment (Iyy_1): 3734803237.2829967       
  Product moment (Izz_1): 1803737092.9280772       
  Product moment (Iyz_1): 9.313225746154785e-10    
  E * Iyy_1: 78555439123265.92
  E * Izz_1: 33228866502282.105
  Neutral axe distance: 89.55154878474053
  Cracking moment: 71010571.15473056
2) No cracking expected for N+M2. Properties:      
  Product moment (Iyy_2): 3734803237.2829967       
  Product moment (Izz_2): 1803737092.9280772       
  Product moment (Iyz_2): 9.313225746154785e-10    
  E * Iyy_2: 78555439123265.92
  E * Izz_2: 33228866502282.105
  Neutral axe distance: -106.18197088429847        
  Cracking moment: -70040051.6471089
#############################################

Use example:
```python
from shapely import Polygon

from structuralcodes import codes, materials
from structuralcodes.geometry import SurfaceGeometry
from structuralcodes.sections._generic import GenericSection
from structuralcodes.sections._reinforcement import add_reinforcement_line

# CREATE THE SECTION ########
codes.set_design_code(design_code='ec2_2004')
concrete = materials.concrete.create_concrete(fck=25)
reinforcemnet = materials.reinforcement.create_reinforcement(
    fyk=500,
    Es=200000,
    density=7850,
    ftk=500,
    epsuk=0.07,
)
poly = Polygon(((0, 0), (350, 0), (350, 500), (0, 500)))
geo = SurfaceGeometry(poly, concrete)
geo = add_reinforcement_line(
    geo, (50, 450), (300, 450), 12, reinforcemnet, n=3
)
geo = add_reinforcement_line(geo, (50, 50), (300, 50), 20, reinforcemnet, n=6)
sec = GenericSection(
    geo,
)

sec.geometry = sec.geometry.translate(-175, -250)

# CREATE THE SECTION ########

print(sec.cracked_properties(-300 * 1e3, 30 * 1e6, -60 * 1e6))
```

**Comment by MestreCarlos** [comment]
I had to make a small adjustment in structuralcodes_geometry.py in the translate and rotate functions because the _reinforced_concrete property changed to False when I used them in the line:
```python sec.geometry = sec.geometry.translate(-175, -250) ```

**Comment by mortenengen** [comment]
Thanks for the contribution @MestreCarlos 😃 When reviewing this I think it is important that we answer the question: are the cracked properties really properties of the section, or are they results of a section analysis? In my opinion, the gross properties are indeed properties of the section, but the cracked properties are instead results from an analysis of the section subject to a set of loads.

This is why, in my opinion, we should see this PR in relation to #161 where we run an analysis on the section. Instead of introducing a separate method for calculating the cracked properties, we should return these properties in the result object from the section analysis. One property that we do not get directly from this kind of analysis is the cracking moment, but I guess this is quite straight forward to calculate from a tensile strength and the gross properties?

I therefore suggest that we close this for now, and instead focus on implementing a robust method for calculating the strain plane for an arbitrary set of axial force and biaxial bending as in #161.

**Comment by mortenengen** [comment]
I am picking up this one again. I think there are at least two sides to this topic:

1. The cracked properties, depend on the loading, and are therefore not really properties, but more the response of the section under some assumptions.

2. The cracked properties calculated assuming linear elasticity in the compressive zone, no tensile stresses in the concrete, and linear elastic reinforcement, are results that engineers would expect to be able to calculate with a library like structuralcodes.

Realizing this second point, and also recognizing the effort you have already put into preparing the first draft, is why I think we should move further with implementing this feature.

However, due to the first point, I suggest that we do not implement it as a method on the `GenericSection`, but as a separate utility function, and without considering loads on the section.

In this utility function, we should clearly state that we are dealing with a special case, where we assign linear elastic constitutive laws for all materials, neglect tension in surface geometries, and from there calculate the resulting properties. We should state this both in the name (e.g. `calculate_elastic_cracked_properties(section: GenericSection, theta: float = 0)`) and in the docstring. We could e.g. put this utility function in a separate module `_rc_utils.py` in the `sections` sub-package.

In the original proposal in the current PR, we also have the dependency on loads, but I suggest that we skip this herein, and let that dependency be handled by the method for calculating the strain plane in #161.

Would you like to give the alternative implementation a try, @MestreCarlos ? Please share your thoughts, and let me know if I can assist any further progress 😃

**Comment by MestreCarlos** [comment]
I created a new pull request with this thread.  #210
I have not been able to link the new branch I developed to this pull request. I don't know if it is possible

**Comment by mortenengen** [comment]
The work is continued in #210.

**Pull request closed without merging**
